version: 2
jobs:
  build:
    working_directory: ~/k
    machine: true
    steps:
      - checkout
      - run:
          name: Building
          command: |
            cd cmd
            docker build -t $IMAGE_NAME .
      - run:
          name: Deploying
          command: |
            docker save -o $CONTAINER_NAME.tar $IMAGE_NAME
            scp $CONTAINER_NAME.tar $DROPLET_USER@$DROPLET_IP:/$DROPLET_USER
            scp .circleci/roll-out.sh $DROPLET_USER@$DROPLET_IP:/$DROPLET_USER
